services:
  - type: web
    name: gg-api
    env: docker
    region: oregon
    plan: standard
    branch: main
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    buildFilter:
      paths:
        - src/**/*.ts
        - package.json
        - package-lock.json
        - Dockerfile
        - tsconfig.json
